name: Deploy

on:
  push:
    branches:
      - master

jobs:
  unit-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: akhileshns/heroku-deploy@v3.12.12
        with:
          args: deploy
          heroku_api_key: ${{secrets.HEROKU_API_KEY}}
          heroku_app_name: "typescript-blog-cms-practical"
          heroku_email: "thepunkyone@gmail.com"
